//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualiTech
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Achat()
        {
            this.DetailAchat = new HashSet<DetailAchat>();
        }
    
        public int AchatId { get; set; }
        public int UtilisateurId { get; set; }
        public Nullable<int> FournisseurId { get; set; }
        public System.DateTime Date_Achat { get; set; }
        public decimal Montant_Total { get; set; }
    
        public virtual Fournisseurs Fournisseurs { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailAchat> DetailAchat { get; set; }
    }
}
