//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualiTech
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailVente
    {
        public int ID_DetailVente { get; set; }
        public int VenteId { get; set; }
        public int ArticleId { get; set; }
        public string Reference { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> PrixUnitaire { get; set; }
        public Nullable<int> Quantite { get; set; }
        public decimal Montant_Produit { get; set; }
        public Nullable<int> TypeArticleId { get; set; }
    
        public virtual Articles Articles { get; set; }
        public virtual Vente Vente { get; set; }
        public virtual TypeArticle TypeArticle { get; set; }

        internal static bool Any(Func<object, bool> value)
        {
            throw new NotImplementedException();
        }
    }
}
