//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualiTech
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vente()
        {
            this.DetailVente = new HashSet<DetailVente>();
        }
    
        public int VenteId { get; set; }
        public int UtilisateurId { get; set; }
        public Nullable<int> ClientID { get; set; }
        public System.DateTime Date_Vente { get; set; }
        public decimal Montant_Total { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailVente> DetailVente { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
    }
}
